# 系统矩阵配置（标称）

state_transition_matrix:
  # A矩阵 - 16x16 状态转移矩阵
  diagonal: 0.8  # 对角线（状态惯性）
  interactions:
    # 资源状态交互
    - [0, 2, 0.1]    # 人员利用 -> 床位占用
    - [1, 0, 0.05]   # 床位占用 -> 设备利用
    - [2, 3, -0.1]   # 库存 -> 人员效率(抑制)
    - [3, 1, 0.08]   # 设备利用 -> 库存消耗

    # 财务状态交互
    - [4, 0, 0.15]   # 床位占用 -> 现金储备
    - [5, 0, 0.2]    # 床位占用 -> 利润率
    - [5, 9, 0.15]   # 患者满意度 -> 利润率
    - [6, 5, 0.3]    # 利润率 -> 负债率
    - [7, 2, -0.1]   # 人员利用 -> 成本效率(抑制)

    # 服务质量状态交互
    - [8, 0, -0.1]   # 床位占用 -> 等待时间(负向)
    - [9, 2, -0.2]   # 人员利用 -> 患者满意度(负向)
    - [9, 8, -0.3]   # 等待时间 -> 患者满意度(负向)
    - [9, 10, 0.4]   # 治疗成功率 -> 患者满意度
    - [10, 1, 0.2]   # 设备利用 -> 治疗成功率
    - [11, 10, 0.3]  # 治疗成功率 -> 安全指数

    # 教育伦理状态交互
    - [12, 9, 0.2]   # 患者满意度 -> 伦理合规
    - [13, 5, 0.15]  # 利润率 -> 分配公平
    - [14, 2, 0.25]  # 人员利用 -> 学习效率
    - [15, 14, 0.3]  # 学习效率 -> 知识传递

control_input_matrix:
  # B矩阵 - 16x17 控制输入矩阵
  doctor_controls:
    - [0, 0, 0.3]    # 资源分配 -> 床位占用
    - [1, 1, 0.25]   # 治疗方案 -> 设备利用
    - [2, 2, 0.2]    # 工作负荷管理 -> 人员利用
    - [9, 3, 0.4]    # 质量控制 -> 患者满意度
    - [10, 1, 0.3]   # 治疗方案 -> 治疗成功率

  intern_controls:
    - [2, 5, 0.3]    # 临床参与 -> 人员利用
    - [9, 6, 0.2]    # 反馈生成 -> 患者满意度
    - [14, 4, 0.5]   # 学习时间 -> 学习效率
    - [15, 7, 0.3]   # 扰动预测 -> 知识传递

  patient_controls:
    - [9, 8, 0.6]    # 满意度反馈 -> 患者满意度
    - [8, 9, 0.4]    # 需求倡导 -> 等待时间
    - [11, 10, 0.3]  # 质量监控 -> 安全指数

  accountant_controls:
    - [4, 11, 0.5]   # 预算控制 -> 现金储备
    - [5, 12, 0.4]   # 成本优化 -> 利润率
    - [6, 13, 0.3]   # 风险缓解 -> 负债率

  government_controls:
    - [5, 14, 0.4]   # 政策指导 -> 利润率
    - [12, 15, 0.6]  # 资金调整 -> 伦理合规
    - [13, 16, 0.5]  # 法规合规 -> 分配公平

disturbance_matrix:
  # E矩阵 - 16x6 扰动输入矩阵
  - [0, 0, 0.3]    # 疫情 -> 床位占用
  - [0, 3, 0.5]    # 需求冲击 -> 床位占用
  - [1, 4, 0.4]    # 供应中断 -> 设备利用
  - [2, 5, 0.4]    # 人员变化 -> 人员利用
  - [4, 1, 0.3]    # 政策变化 -> 现金储备
  - [5, 2, 0.2]    # 经济波动 -> 利润率
  - [8, 3, 0.6]    # 需求冲击 -> 等待时间
  - [9, 0, 0.4]    # 疫情 -> 患者满意度

output_matrix:
  # C矩阵 - 输出矩阵（默认完全观测）
  type: "identity"

feedthrough_matrix:
  # D矩阵 - 直通矩阵（默认零阵）
  type: "zero"