# 系统矩阵配置

state_transition_matrix:
  # A矩阵 - 16x16状态转移矩阵
  # 这里只显示部分配置，实际应该完整定义
  diagonal: 0.8  # 对角线元素（状态惯性）
  interactions:
    - [0, 2, 0.1]   # A[0,2] = 0.1
    - [1, 0, 0.05]  # A[1,0] = 0.05
    - [2, 3, -0.1]  # A[2,3] = -0.1

control_input_matrix:
  # B矩阵 - 16x17控制输入矩阵
  doctor_controls:
    - [0, 0, 0.3]   # B[0,0] = 0.3
    - [2, 1, 0.2]   # B[2,1] = 0.2
    - [9, 3, 0.4]   # B[9,3] = 0.4
  intern_controls:
    - [14, 4, 0.5]  # B[14,4] = 0.5
    - [2, 5, 0.3]   # B[2,5] = 0.3

disturbance_matrix:
  # E矩阵 - 16x6扰动输入矩阵
  - [0, 0, 0.3]   # E[0,0] = 0.3
  - [5, 1, 0.4]   # E[5,1] = 0.4
  - [9, 2, 0.2]   # E[9,2] = 0.2

output_matrix:
  # C矩阵 - 输出矩阵（假设完全观测）
  type: "identity"

feedthrough_matrix:
  # D矩阵 - 直通矩阵
  type: "zero"